### ISSUE TITLE
Amend vulgar bit of the README?

### ISSUE THREAD

**Issue by habnabit** [KOLANICH/alternativez.py#1]
I brought this up on [Pipeline.py](https://github.com/KOLANICH/Pipeline.py/issues/1) but it seems that this phrasing has still been added to new projects: 

>`Python 2` is dead, stop raping its corpse.

While this might be "well-known jargon" in Russian, I suggest using something other than a literal translation into English, as the connotations are vulgar and the intent confusing.

**Comment by KOLANICH** [comment]
>as the connotations are vulgar and the intent confusing.

Just as planned. It makes the effect that it is meant to make. The wordplay is also intended. I'm a bit sorry to disappoint you, but I'm not gonna change the wording for now (may be changed, if you found something that I find funnier than the current wording).
